"""add visitor_id to visits and update relationships

Revision ID: 3b363aec08f5
Revises: c8b8efd7f247
Create Date: 2025-06-08 20:29:26.712597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b363aec08f5'
down_revision = 'c8b8efd7f247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'visits', ['last_visit_id'], ['id'])

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'visitor', ['visitor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visitor_id')

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
