"""Change pesel column to String

Revision ID: 3b41f47c1675
Revises: 7cddcf9b7efa
Create Date: 2025-06-07 16:38:20.793187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b41f47c1675'
down_revision = '7cddcf9b7efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.alter_column('pesel',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=265),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.alter_column('pesel',
               existing_type=sa.String(length=265),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
