"""Add Check-in and Check-out rows

Revision ID: 4e169c378bc5
Revises: 5ae6ba50fcc1
Create Date: 2025-06-07 22:22:58.785838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e169c378bc5'
down_revision = '5ae6ba50fcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('check_out_date', sa.Date(), nullable=False))
        batch_op.drop_constraint(batch_op.f('visitor_last_visit_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('check_out_date', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('check_in_date')

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('visitor_last_visit_id_fkey'), 'visits', ['last_visit_id'], ['id'])
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('check_in_date')

    # ### end Alembic commands ###
