"""Add Visits table

Revision ID: 5ae6ba50fcc1
Revises: 3b41f47c1675
Create Date: 2025-06-07 22:00:27.989809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae6ba50fcc1'
down_revision = '3b41f47c1675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.Enum('VIP', 'BUSINESS', 'BUDGET', name='roomtype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('last_visit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'visits', ['last_visit_id'], ['id'])
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_visit_id')
        batch_op.drop_column('name')

    op.drop_table('visits')
    # ### end Alembic commands ###
